### ISSUE TITLE
Reference-style links aren't transformed into anchor tags

### ISSUE THREAD

**Issue by mattwidmann** [segmentio/metalsmith-excerpts#5]
Given a Markdown file like the following:

```

---
title: Reference-style link demo

---

This includes some [links][] and other [things that should turn into anchor tags][a].

[links]: http://example.com
[a]: http://example.com
```

metalsmith-excerpts just grabs the first portion of text up to the first two newline characters and passes that into marked.  This is why marked doesn't turn the reference-style links into actual anchor tags -- the references for them aren't passed in with the first paragraph.

Ideally, the way to fix this would be to excerpt from the HTML after converting the entire document.  That way, documents that put all of the references at the bottom of the document would still work.  After that, you would need to find the first tag (be it `<p>`, `<pre>`, `<blockquote>`, etc.) in the HTML.  Using cheerio, you can accomplish that with:

``` javascript
var cheerio = require('cheerio');
var $ = cheerio.load(file.contents.toString());
var firstTag = $('*').first().clone();
$('*').replaceWith(firstTag);
file.excerpt = $.html();
```

I think you have to use `clone()` and `replaceWith()` to get the outerHTML of the tag you're selecting.  I might be wrong about this.

**Comment by woodyrew** [comment]
Fixed with #7
