### ISSUE TITLE
Indented first paragraphs are transformed incorrectly

### ISSUE THREAD

**Issue by mattwidmann** [segmentio/metalsmith-excerpts#6]
If the first paragraph of a Markdown file is indented, indicating that it's a code block, like this:

```

---
title: Test code blocks as first paragraphs

---

    This is code

This is not code
```

markdown-excerpts will go through each line and remove leading whitespace, making the code block a normal paragraph block.

**Comment by woodyrew** [comment]
Duplicate of #5
